server:
  port: 8001

spring:
  rabbitmq:
    addresses: 192.168.31.29:5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    ## 是否启用消息确认模式
    publisher-confirms: true
    ## 设置return消息模式, 需要和mandatory一起使用
#    publisher-returns: true
#    template:
#      mandatory: true
    listener:
      simple:
        # 表示消费者消费成功消息后需要手工签收(ack) , 默认是auto
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
